name: kenzy
description: "A new Hospital DZ project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.8+8

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cloud_firestore: ^6.1.0
  firebase_messaging: ^16.0.4
  firebase_database: ^12.1.0
  firebase_storage: ^13.0.4
  firebase_in_app_messaging: ^0.9.0+4
  firebase_analytics: any
  firebase_core: ^4.2.1
  firebase_app_check: ^0.4.1+2
  #  google_sign_in: ^6.3.0
  google_sign_in: ^7.2.0
  #  firedart: ^0.9.8
  cached_network_image: ^3.4.1
  supabase_flutter: ^2.10.3
  flutter_image_compress: ^2.4.0
  lottie: ^3.3.1
  provider: ^6.1.5+1
  fluttertoast: ^9.0.0
  font_awesome_flutter: ^10.9.0

  shared_preferences: ^2.5.3
  avatar_glow: ^3.0.1
  url_launcher: ^6.3.2
  carousel_slider: ^5.1.1
  image_picker: ^1.2.1
  intl_phone_field: ^3.2.0
  intl: ^0.20.2
  mobile_scanner: ^7.0.1
  ticket_widget: ^1.0.2
  readmore: ^3.0.0
  dart_date: ^1.5.3
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  rename: ^3.1.0
  marqueer: ^2.1.0
  screenshot: ^3.0.0
  email_validator: ^3.0.0
  flutter_islamic_icons: ^1.0.2
  geocoding: ^4.0.0
  map_launcher: ^4.4.2
  open_location_picker: ^1.1.0
  jiffy: ^6.4.3
  google_fonts: ^6.3.1
  googleapis_auth:
  path: ^1.9.1
  timelines: ^0.1.0
  animated_flip_counter: ^0.3.4
  pretty_qr_code: ^3.5.0
  http: ^1.6.0
  decimal: ^3.2.4
  openfoodfacts: ^3.27.0
  #  video_player: ^2.9.2
  chewie: ^1.12.1
  flutter_easyloading: ^3.0.5
  wakelock_plus: ^1.4.0
  faker: ^2.2.0
  timeago: ^3.7.1
  objectbox: ^4.3.1
  objectbox_flutter_libs: ^4.3.1
  network_info_plus: ^7.0.0
  multicast_dns: ^0.3.3
  percent_indicator: ^4.2.5
  icons_plus: ^5.0.0
  feedback: ^3.2.0
  win32: ^5.15.0
  msix: ^3.16.12
  device_info_plus: ^12.3.0
  pincode_input_fields: ^1.0.3
  syncfusion_flutter_barcodes: ^30.2.6
  linked_scroll_controller: ^0.2.0
  #  excel: ^4.0.6
  country_flags: ^3.3.0
  google_mobile_ads: ^6.0.0
  permission_handler: ^12.0.1
  file_picker: ^10.3.3
  vibration: ^3.1.3
  #  window_manager: ^0.4.2
  string_extensions: ^0.7.4
  #  fluent_ui: ^4.10.0
  firebase_auth: ^6.1.2
  #  calendar_timeline: ^1.1.3
  flutter_slidable: ^4.0.1
  connectivity_plus: ^7.0.0
  #  media_kit: ^1.1.11 # Primary package.
  #  media_kit_video: ^1.2.5 # For video rendering.
  #  media_kit_libs_video: ^1.0.5 # Native video dependencies.
  #  media_kit_libs_audio: ^1.0.5 # Native audio dependencies.
  flutter_avif: ^3.0.0
  youtube_player_flutter: ^9.1.3
  #  webfeed_plus: ^1.1.2
  rename_app: ^1.6.5
  call_log: ^6.0.1
  easy_date_timeline: ^2.0.9
  multi_view_calendar: ^1.0.2
  calendar_planner_view: ^0.3.3
  table_calendar: ^3.2.0
  flutter_hooks: ^0.21.3+1
  #  flutter_bloc: ^9.1.1
  gradient_borders: ^1.0.2
  plugin_platform_interface: ^2.1.8
  smooth_page_indicator: ^1.2.1
  flutter_card_swiper: ^7.0.2
  dynamic_flutter_form: ^1.0.2
  syncfusion_flutter_calendar: ^30.2.7
  flutter_native_splash: ^2.4.7
  fl_chart: ^0.70.0
  syncfusion_flutter_datagrid: ^30.2.7
  pdf: ^3.11.3
  printing: ^5.14.2
  flutter_pdfview: ^1.3.1
  window_manager: ^0.5.1
  flutter_single_instance: ^1.1.2

  uuid: ^4.5.1
  cryptography: ^2.9.0
  collection: ^1.19.1
  pointycastle: ^4.0.0
  video_compress: ^3.1.4

  socket_io_client: ^3.1.3
  flutter_local_notifications: ^19.5.0
  flutter_osm_plugin: ^1.4.3



  path_provider: ^2.1.5

  image: ^4.5.4

  #  # Maps (OpenStreetMap)
  #  flutter_map: ^8.2.2
  #  latlong2: ^0.9.1
  #  geolocator: ^14.0.2

  flutter_svg: ^2.0.9





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  objectbox_generator: ^4.3.0
  build_runner: ^2.4.15
  innosetup: ^0.1.3



flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_hopital.png"
  #  image_path: "assets/images/ic_launcher/1024.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo_hopital.png"
    #    image_path: "assets/images/ic_launcher/1024.png"
    adaptive_icon_foreground: "assets/images/logo_hopital.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo_hopital.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo_hopital.png"

flutter_native_splash:
  # Configuration Android
  android: true
  background_image: assets/icon/splash3.png
  android_12:
    image: assets/icon/splash3.png
    icon_background_color: "#FFFFFF"


  # Configuration iOS
  ios: true
  image: assets/icon/splash3.png
  color: "#FFFFFF"


flutter:
  uses-material-design: true
  generate: true



  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Bold.ttf
        - asset: assets/fonts/Oswald-ExtraLight.ttf
        - asset: assets/fonts/Oswald-SemiBold.ttf
        - asset: assets/fonts/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald-Light.ttf
        - asset: assets/fonts/Oswald-Medium.ttf
    - family: ArbFONTS
      fonts:
        - asset: assets/fonts/ArbFONTS-khalaad-al-arabeh.ttf
        - asset: assets/fonts/ArbFONTS-Al-Jazeera-Arabic-Bold.ttf
        - asset: assets/fonts/ArbFONTS-Al-Jazeera-Arabic-Bold-1.ttf
        - asset: assets/fonts/ArbFONTS-Al-Jazeera-Arabic-Light.ttf
        - asset: assets/fonts/ArbFONTS-Al-Jazeera-Arabic-Regular.ttf
        - asset: assets/fonts/NizarBBCKurdish-Bold.ttf

  assets:
    - assets/
    - assets/100.png
    - assets/101.png
    - assets/star.png
    - assets/location.png
    - assets/heart.png
    - assets/lotties/
    - assets/images/ic_launcher/1024.png
    - assets/images/744878.png
    - assets/images/icon.png
    - assets/firebase_logo.png
    - assets/google_logo.png
    - assets/logos/
    #    - assets/icon/playstore.png
    #    - assets/icon/appstore.png
    - assets/icon/icon.png
    - assets/logos/djezzy.png
    - assets/logos/inconnu.png
    - assets/logos/mobilis.png
    - assets/logos/ooredoo.png
    - assets/splash_logo.png
    - assets/seasons/
    - assets/photos/
    - assets/images/logo_hopital.png
    - assets/photos/hopital/
    - assets/photos/hopital/d (1).jpg
    - assets/photos/hopital/m1 (5).jpg
    - assets/photos/hopital/tt (7).jpg
    - assets/lotties/1 (2).json
    - webHospital/img/logo_hopital.png
    - webHospital/img/screenshot1.png
    - webHospital/img/screenshot2.png
    - webHospital/img/screenshot3.png
    - assets/photos/hopital/pitol/

flutter_localizations:
sdk: flutter


intl: any
gen-l10n:
  enabled: true
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations




  flutter_gen:
    integrations:
      flutter_svg: true
      flare_flutter: true
      rive: true
      lottie: true

  flutter_intl:
    enabled: true
    class_name: S
    main_locale: en
    arb_dir: lib/l10n
    output_dir: lib/generated/intl



