// ObjectBox model registration checklist for the planning feature.
//
// Add the following entities to the application's ObjectBox model generation
// entry point before running `dart run build_runner build`:
//
// - PlanningSnapshotEntity
// - PlanningAssignmentEntity
// - RotationConfigurationEntity
// - RotationPeriodEntity
// - PlanningOverrideEntity
//
// IMPORTANT: Keep the generated model IDs stable once released. Never delete
// or recycle an ObjectBox entity/property ID. Existing legacy entities must
// remain in the model until the migration has been verified in production.
//
// The actual generated `objectbox.g.dart` file must be regenerated by the
// project's ObjectBox build process rather than hand-edited.
