// ObjectBox model registration checklist for the planning feature.
//
// The planning entities are discovered by ObjectBox through the application's
// generated model entry point. Keep this file as the single checklist used by
// CI/model validation when entities are added or removed.
//
// Required planning entities:
// - PlanningSnapshotEntity
// - PlanningAssignmentEntity
// - RotationStateSnapshotEntity
// - RotationConfigurationEntity
// - RotationPeriodEntity
// - PlanningOverrideEntity
// - PlanningRevisionEntity
//
// IMPORTANT: Keep generated model IDs stable once released. Never delete or
// recycle an ObjectBox entity/property ID. Existing legacy entities must
// remain in the model until migration has been verified in production.
//
// The generated `lib/objectbox.g.dart` file must always be regenerated by the
// project's ObjectBox build process, never hand-edited.
