// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-3n3_btslk-L9hnXmi5ZaZPFNWb9V7pw',
    appId: '1:536701149573:web:028c8807abb30fa11924ec',
    messagingSenderId: '536701149573',
    projectId: 'hotel-f84db',
    authDomain: 'hotel-f84db.firebaseapp.com',
    storageBucket: 'hotel-f84db.firebasestorage.app',
    measurementId: 'G-PKJVN71LT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBygH4-4mmUJe-6UL7iExAPxNwiVv3WIlA',
    appId: '1:536701149573:android:6e3f7c230003d4321924ec',
    messagingSenderId: '536701149573',
    projectId: 'hotel-f84db',
    storageBucket: 'hotel-f84db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOq4jkgM-GgtG-X8v6XYLZxDTn_tmL0o4',
    appId: '1:536701149573:ios:22251491404dd1711924ec',
    messagingSenderId: '536701149573',
    projectId: 'hotel-f84db',
    storageBucket: 'hotel-f84db.firebasestorage.app',
    iosBundleId: 'com.hotel.dz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOq4jkgM-GgtG-X8v6XYLZxDTn_tmL0o4',
    appId: '1:536701149573:ios:22251491404dd1711924ec',
    messagingSenderId: '536701149573',
    projectId: 'hotel-f84db',
    storageBucket: 'hotel-f84db.firebasestorage.app',
    iosBundleId: 'com.hotel.dz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-3n3_btslk-L9hnXmi5ZaZPFNWb9V7pw',
    appId: '1:536701149573:web:6934771adcb3a53f1924ec',
    messagingSenderId: '536701149573',
    projectId: 'hotel-f84db',
    authDomain: 'hotel-f84db.firebaseapp.com',
    storageBucket: 'hotel-f84db.firebasestorage.app',
    measurementId: 'G-ZG3HR845KN',
  );

}