-- Keep the ObjectBox schema while retaining the remote adapter fields used by
-- SupabasePlanningDatasource.
ALTER TABLE public.planning_configurations
  ADD COLUMN payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  ALTER COLUMN name SET DEFAULT '',
  ALTER COLUMN team_order_json SET DEFAULT '[]',
  ALTER COLUMN cycle_json SET DEFAULT '[]',
  ALTER COLUMN reference_date SET DEFAULT NULL;

ALTER TABLE public.planning_assignments
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.rotation_state_snapshots
  ADD COLUMN snapshot_id uuid REFERENCES public.planning_snapshots(id) ON DELETE CASCADE,
  ADD CONSTRAINT rotation_state_snapshots_snapshot_id_key UNIQUE (snapshot_id);

-- Requested development mode: no RLS or policies are applied.
DO $$
DECLARE table_record record;
BEGIN
  FOR table_record IN SELECT tablename FROM pg_tables WHERE schemaname = 'public' LOOP
    EXECUTE format('ALTER TABLE public.%I DISABLE ROW LEVEL SECURITY', table_record.tablename);
  END LOOP;
END $$;

NOTIFY pgrst, 'reload schema';
